//; A math game.
Welcome to Math Guess!
Elavuate the expressions.
1 + 2 - 5x, if x = 5
;let>userinput=0
;let>mathsection=1+2-5*5
;prompt> :userinput
;if>{userinput}=={mathsection}| Yah your right!
;if>{userinput}!={mathsection}|Wrong!
1 + 123*3x - 5x + 1, if x = 1
;let>mathsection=1 + 123*3*1 - 5*1 +1
;prompt> :userinput
;if>{userinput}=={mathsection}| Yah your right!
;if>{userinput}!={mathsection}|Wrong!